version: "3.9"

services:
  appgo:
    build: ./papoco
    ports: 
      - "3000:3000"
    volumes:
      - .:/
  
  # ngrok:
  #   image: ngrok:latest
  #   environment:
  #     - NGROK_PORT=3000
  #   ports:
  #     - "4040:4040"
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 10s
    environment:
      POSTGRESS_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postdb
    volumes:
      - "./data:/var/lib/postgresql/data"
